# Generated by Django 3.2 on 2023-04-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Код подтверждения'),
        ),
    ]
